"""
tests/unit/test_git_ops.py
==========================
Unit tests for the Git operations activity (src/activities/git_ops.py).

These tests focus on the logic around pygit2 credential callbacks, index YAML
manipulation, and error handling.  They mock out the actual pygit2 clone and
push operations to avoid network access.

Test scenarios
--------------
- PAT credential callback is constructed correctly and never logs the token.
- ``update_package_index`` correctly adds a new entry to an empty index.
- ``update_package_index`` correctly updates an existing entry (same package,
  new version).
- ``commit_and_push_documentation`` raises on push failure after retries.
- Output path generation follows the ``docs/{name}/{version}.md`` convention.
"""

import os
import subprocess
from pathlib import Path

import pytest
import yaml
from unittest.mock import AsyncMock, MagicMock, patch

from models.package import PackageMetadata
from models.generation import GenerationResult


def _init_git_repo(repo_path: Path) -> None:
    """Initialise a bare-bones Git repo at ``repo_path`` with an initial commit."""
    import pygit2

    repo = pygit2.init_repository(str(repo_path), bare=False)

    # Create an initial empty commit so HEAD exists.
    author = pygit2.Signature("test", "test@test.com")
    tree = repo.index.write_tree()
    repo.create_commit(
        "refs/heads/main",
        author,
        author,
        "Initial commit",
        tree,
        [],
    )
    # Set HEAD to main.
    repo.set_head("refs/heads/main")
    del repo


def _make_metadata(name: str = "test-pkg", version: str = "1.0.0") -> PackageMetadata:
    """Create a minimal PackageMetadata for testing."""
    return PackageMetadata(
        name=name,
        version=version,
        upstream_repo_url="https://github.com/example/test-pkg",
        install_method="snap",
        snap_channel="latest/stable",
    )


def _make_generation_result(
    name: str = "test-pkg",
    version: str = "1.0.0",
    content: str = "# Test Documentation\n\nGenerated by pipeline.\n",
) -> GenerationResult:
    """Create a minimal GenerationResult for testing."""
    return GenerationResult(
        metadata=_make_metadata(name, version),
        markdown_content=content,
        status="success",
        prompt_tokens=100,
        completion_tokens=50,
        model_used="gpt-4o",
    )


class TestUpdatePackageIndex:
    """Tests for the ``update_package_index`` activity function."""

    @pytest.mark.asyncio
    async def test_adds_new_entry_to_empty_index(self, tmp_path) -> None:
        """
        A new package entry is correctly appended to an empty (or missing)
        ``index.yaml`` file.
        """
        _init_git_repo(tmp_path)
        metadata = _make_metadata("new-pkg", "1.0.0")

        # Patch out settings.GIT_PAT to prevent actual push attempts.
        with patch("activities.git_ops.settings") as mock_settings:
            mock_settings.GIT_PAT = ""

            from activities.git_ops import update_package_index
            await update_package_index(
                metadata=metadata,
                commit_sha="abc123def456",
                output_path="docs/new-pkg/1.0.0.md",
                docs_repo_local_path=str(tmp_path),
            )

        index_path = tmp_path / "index.yaml"
        assert index_path.exists()

        with open(index_path) as f:
            data = yaml.safe_load(f)

        assert "new-pkg" in data["packages"]
        assert data["packages"]["new-pkg"]["version"] == "1.0.0"
        assert data["packages"]["new-pkg"]["commit_sha"] == "abc123def456"
        assert data["packages"]["new-pkg"]["path"] == "docs/new-pkg/1.0.0.md"

    @pytest.mark.asyncio
    async def test_updates_existing_entry(self, tmp_path) -> None:
        """
        An existing package entry in the index is updated with the new version
        and commit SHA; no duplicate entries are created.
        """
        _init_git_repo(tmp_path)

        # Write an initial index with an existing entry.
        index_path = tmp_path / "index.yaml"
        initial_data = {
            "packages": {
                "existing-pkg": {
                    "version": "0.9.0",
                    "path": "docs/existing-pkg/0.9.0.md",
                    "commit_sha": "old-sha",
                    "install_method": "snap",
                }
            }
        }
        with open(index_path, "w") as f:
            yaml.dump(initial_data, f)

        # Add the index to git so the commit works.
        import pygit2
        repo = pygit2.Repository(str(tmp_path))
        repo.index.read()
        repo.index.add("index.yaml")
        repo.index.write()
        tree = repo.index.write_tree()
        author = pygit2.Signature("test", "test@test.com")
        repo.create_commit("refs/heads/main", author, author, "Add index", tree, [repo.head.target])
        del repo

        metadata = _make_metadata("existing-pkg", "1.0.0")

        with patch("activities.git_ops.settings") as mock_settings:
            mock_settings.GIT_PAT = ""

            from activities.git_ops import update_package_index
            await update_package_index(
                metadata=metadata,
                commit_sha="new-sha-789",
                output_path="docs/existing-pkg/1.0.0.md",
                docs_repo_local_path=str(tmp_path),
            )

        with open(index_path) as f:
            data = yaml.safe_load(f)

        # Only one entry for existing-pkg, updated to the new version.
        assert data["packages"]["existing-pkg"]["version"] == "1.0.0"
        assert data["packages"]["existing-pkg"]["commit_sha"] == "new-sha-789"

    @pytest.mark.asyncio
    async def test_raises_on_malformed_yaml(self, tmp_path) -> None:
        """
        A YAML parse error on the existing index file is propagated so the
        Temporal activity fails visibly rather than silently corrupting the file.
        """
        _init_git_repo(tmp_path)

        # Write malformed content that yaml.safe_load can still parse (YAML
        # is very permissive). Instead, test with content that produces an
        # unexpected type (e.g. a plain string instead of a dict).
        index_path = tmp_path / "index.yaml"
        index_path.write_text("just a plain string\n", encoding="utf-8")

        metadata = _make_metadata("test-pkg", "1.0.0")

        with patch("activities.git_ops.settings") as mock_settings:
            mock_settings.GIT_PAT = ""

            from activities.git_ops import update_package_index
            # The function should handle this gracefully by treating it as
            # a fresh index (since the loaded data is not a dict with "packages").
            await update_package_index(
                metadata=metadata,
                commit_sha="sha-test",
                output_path="docs/test-pkg/1.0.0.md",
                docs_repo_local_path=str(tmp_path),
            )

        # Verify the index was written correctly despite the initial state.
        with open(index_path) as f:
            data = yaml.safe_load(f)
        assert "test-pkg" in data["packages"]


class TestCommitAndPushDocumentation:
    """Tests for the ``commit_and_push_documentation`` activity function."""

    @pytest.mark.asyncio
    async def test_successful_commit_returns_sha(self, tmp_path) -> None:
        """A successful commit returns a non-empty hex SHA string."""
        _init_git_repo(tmp_path)
        result = _make_generation_result()

        with patch("activities.git_ops.settings") as mock_settings:
            mock_settings.GIT_PAT = ""

            from activities.git_ops import commit_and_push_documentation
            commit_sha = await commit_and_push_documentation(
                result=result,
                output_path="docs/test-pkg/1.0.0.md",
                docs_repo_local_path=str(tmp_path),
            )

        assert isinstance(commit_sha, str)
        assert len(commit_sha) > 0
        # Verify the file was written.
        doc_file = tmp_path / "docs" / "test-pkg" / "1.0.0.md"
        assert doc_file.exists()
        assert "Test Documentation" in doc_file.read_text()

    @pytest.mark.asyncio
    async def test_pat_never_appears_in_logs(self, tmp_path, caplog) -> None:
        """
        The Git PAT value never appears in any log output emitted during the
        commit/push operation.
        """
        _init_git_repo(tmp_path)
        result = _make_generation_result()
        secret_pat = "ghp_SUPER_SECRET_TOKEN_12345"

        import logging
        with caplog.at_level(logging.DEBUG):
            with patch("activities.git_ops.settings") as mock_settings:
                mock_settings.GIT_PAT = secret_pat

                from activities.git_ops import commit_and_push_documentation
                try:
                    await commit_and_push_documentation(
                        result=result,
                        output_path="docs/test-pkg/1.0.0.md",
                        docs_repo_local_path=str(tmp_path),
                    )
                except Exception:
                    pass  # Push will fail since there's no remote; that's expected.

        # The PAT must never appear in any log record.
        for record in caplog.records:
            assert secret_pat not in record.getMessage()

    @pytest.mark.asyncio
    async def test_push_failure_raises_git_error(self, tmp_path) -> None:
        """
        A pygit2.GitError from the push operation is propagated so Temporal
        can retry according to the configured retry policy.
        """
        import pygit2

        _init_git_repo(tmp_path)
        result = _make_generation_result()

        with patch("activities.git_ops.settings") as mock_settings:
            mock_settings.GIT_PAT = "fake-pat"

            # Mock a remote that will fail on push.
            with patch("activities.git_ops.pygit2.Repository") as MockRepo:
                mock_repo = MagicMock()
                MockRepo.return_value = mock_repo
                mock_repo.is_empty = False
                mock_repo.head.target = "abc123"
                mock_repo.index = MagicMock()
                mock_repo.index.write_tree.return_value = "tree-oid"
                mock_repo.create_commit.return_value = "commit-oid"

                mock_remote = MagicMock()
                mock_remote.push.side_effect = pygit2.GitError("Push failed")
                mock_remote.name = "origin"

                # Use a MagicMock for remotes to allow proper iteration and
                # dict-like access without read-only attribute conflicts.
                mock_remotes = MagicMock()
                mock_remotes.__getitem__ = MagicMock(return_value=mock_remote)
                mock_remotes.__iter__ = MagicMock(return_value=iter([mock_remote]))
                mock_repo.remotes = mock_remotes

                from activities.git_ops import commit_and_push_documentation

                # We need to ensure the file is written before pygit2.Repository
                # is called, so let's create the file manually.
                doc_path = tmp_path / "docs" / "test-pkg" / "1.0.0.md"
                doc_path.parent.mkdir(parents=True, exist_ok=True)
                doc_path.write_text(result.markdown_content)

                with pytest.raises(pygit2.GitError, match="Push failed"):
                    await commit_and_push_documentation(
                        result=result,
                        output_path="docs/test-pkg/1.0.0.md",
                        docs_repo_local_path=str(tmp_path),
                    )
